### ISSUE TITLE
how  i can use  1-to-many and UDP-to-UDP proxy?

### ISSUE THREAD

**Issue by notedit** [cargomedia/janus-gateway-rtpbroadcast#103]
can you give a example

**Comment by kris-lab** [comment]
In simple words, if you have 2 janus instances with `janus-gateway-rtpbroadcast` plugin then:
- assign roles to your instances: e.g. 1st -> `origin` (for publishers) and 2nd -> `edge` (for subscribers)
- on the `origin` you need to create the `mountpoint` as usual with `create` end-point (will return dynamic audio/video ports for streams).
- on the `edge` you need to also create the `mountpoint` as usual with `create` end-point (will return dynamic audio/video ports for streams).
- then you need to let know the `origin` where to proxy the mountpoint streams. This must be done with [watch-udp](https://github.com/cargomedia/janus-gateway-rtpbroadcast#watch-udp) end-point on the `origin`. Please note that the `edge` mountpoint should have the same number of streams like the `origin` mountpoint. The `watch-udp` must be done once you will create mountpoint on the edge and the audio/video port pairs are known.

I would suggest to introduce a simple orchestration layer if you have more instances in the pool.

Hope you find this helpful!

**Comment by kris-lab** [comment]
please reopen if needed
