### ISSUE TITLE
Add support for mountpoint create with provided audio/video port pairs

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/janus-gateway-rtpbroadcast#104]
Depends on https://github.com/cargomedia/janus-gateway-rtpbroadcast/issues/105

TODO:
- [ ] allow to create mountpoint with fixed audio/video port pairs per stream
- [ ] make allowed fixed ports configurable (similar to dynamic ports)

It will allow to run multiple `janus` instances as `origin` role in cluster mode, where each instance would bind to the same IP/port.

The main goal is to get rid of SPOF

**Comment by njam** [comment]
Closing janus-cluster tickets
