### ISSUE TITLE
Add support to reuse IP/port for UDP server

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/janus-gateway-rtpbroadcast#105]
Part of #104 

Will allow to run multiple janus instances with replicated `mountpoint`.

---

see http://stackoverflow.com/a/14388707

---

Notes to myself http://hacked10bits.blogspot.co.uk/2014/12/udp-binding-and-port-reuse-in-linux.html
> Regarding the context for this problem, one might be led to ask why I needed a "real" network interface to run multiple SITL instances on a single machine. It turns out that the loopback interface (the one typically with address 127.0.0.1, used for interprocess communications on the local machine) does not support broadcast. There are apparently very good technical reasons for this, but I did not delve deeply into those. It is, however, possible to create a virtual Ethernet interface and even a virtual bridge, and those do support broadcasts.

**Comment by njam** [comment]
Closing janus-cluster tickets
