### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/janus-gateway-rtpbroadcast#116]
Ideas:
- introduce JSON based logging
- store all related info: thread-ID, mountpoint-ID, session-ID, plugin-ID etc.

cc @njam @tomasz

**Comment by njam** [comment]
What could be great is to pass a logging "context" to the WebSocket URL, store it on the connection, and then add it to any log entry related to that connection.
Like it's done in cm-janus: https://github.com/cargomedia/cm-janus#logging

**Comment by njam** [comment]
Closing for the moment
