### ISSUE TITLE
Performance: investigate throughput throttling

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/janus-gateway-rtpbroadcast#12]
We have measured the top throughput of single Janus process. It should be investigated what cause the limits and high CPU usage?

See more:
- https://groups.google.com/forum/#!topic/meetecho-janus/lgGmXRXwhzA
- https://docs.google.com/spreadsheets/d/1ViHanQXDHRkLsToYG3SOH2W-7VqZGWLu7nYselx9fWs/edit

Benchmark showed the limit of 300Mbit per Janus instance (for more details about hardware please see URLs)

**Comment by kris-lab** [comment]
Maybe this ticket is somehow related to our packets loss above 300Mbits http://serverfault.com/questions/691723/extreme-udp-packet-loss-at-300mbit-14-but-tcp-800mbit-w-o-retransmits

**Comment by landswellsong** [comment]
@kris-lab will look at it this evening

**Comment by kris-lab** [comment]
Current measured throughput is `650Mbits` for:
- Debian8/Jessie 
- by applying network tuning https://github.com/cargomedia/puppet-packages/pull/1374
- on `2xE5-2690-V2-DecaCore/32GB/10Gbits`

By applying scaling approach https://github.com/cargomedia/puppet-cargomedia/issues/1080 we do workaround the throughput limitation.

Also native Janus/streaming plugin improvement might increase the throughput https://github.com/meetecho/janus-gateway/pull/568

**Comment by kris-lab** [comment]
Closing for now. It is not the blocking issues. I believe it can be improved in many direction in the future.
