### ISSUE TITLE
Heads up: reliable multicast is being proposed for inclusion in upstream

### ISSUE THREAD

**Issue by cmacq2** [cargomedia/janus-gateway-rtpbroadcast#133]
I proposed a PR for Janus which introduces additional configuration options to bind RTP/RTSP inputs of the streaming plugin to a particular network interface. This is particularly relevant for streaming multicast sources in multi-homed devices (i.e. multiple network ports) but may also be more generally useful in the case of unicast sources (to avoid binding to all network interfaces unnecessarily and use just the one that is actually needed).

You may be interested in backporting and participating in development on PR 776 upstream: https://github.com/meetecho/janus-gateway/pull/776

**Comment by kris-lab** [comment]
@cmacq2 many thanks for great work and update here. I will have a look on integration asap!

`janus-gateway-rtpbroadcast` implements 2 methods of media distribution: RTP/UDP -> WebRTC and RTP/UDP -> RTP/UDP. The 2nd one allows for simple scalability by replicating UDP packets + keeps standard Janus WebSockets signaling layer. 

We have been working (not finished yet) on janus-cluster scenarios and proposed 3 roles: `Origin` -> `Repeater(s)` -> `Edge(s)` (see e.g. https://github.com/cargomedia/janus-cluster-manager/issues/27#issuecomment-233928756). In the simplest scenario, all 3 roles run on the same bare metal server with ration: 1 x `Origin` -> 1 x `Repeater` -> 20 x `Edges`. It allows to increase throughput up to 6Gbits (my tests) and lower CPU usage and kernel load. In such scenario, each `Edge` instances listen on different ports and `Repeater` push replicated packages for each `Edge` separately - many kernel calls.

So, I am wondering if your improvement could help me in lowering kernel load in such workflow. I can imagine that e.g. all `Edge` instances would bind to multicast address/port and `Repeater` would push UDP packets only once to the kernel - this would happen on `localhost`.

Please correct me if I am wrong. I haven’t look on your code and possible solutions yet.

**Comment by cmacq2** [comment]
> So, I am wondering if your improvement could help me in lowering kernel load in such workflow.

That is not really what PR 760 addresses. What the PR does is to enable you to configure which network port is used when joining a multicast IP group *or* restricting what interface Janus will listen for unicast RTP sources. 

What that buys you is the ability to receive RTP on one network interface and output WebRTC on another. In combination with multicast, with this new multi-homed capability you could build a `N` x `M` + 1 setup, with `N` sources being routed to `M` Janus gateways with a load balancer in front, between the Janus gateways and the connecting WebRTC clients. That could reduce load on each separate Janus instance quite a bit, and lets you leverage the hardware capabilities & link-layer protocol provisions of things like switches. Essentially you'd get some more ROI out of the hardware you'd probably bought anyway (a big switch) and you don't have to worry about forwarding inputs to your `Edge` Janus gateways.
