### ISSUE TITLE
about janus cluster

### ISSUE THREAD

**Issue by kangshaojun** [cargomedia/janus-gateway-rtpbroadcast#135]
hi kris-lab
can janus-gateway-rtpbroadcast realization the janus  cluster?
fore example:
client--->janus-gateway-rtpbroadcast---> janus-gateway-rtpbroadcast---->client

**Comment by njam** [comment]
Unfortunately I can't help you with this.
You can try reaching out to Chris directly: https://github.com/kris-lab
