### ISSUE TITLE
is this project maintained and used in production?

### ISSUE THREAD

**Issue by notedit** [cargomedia/janus-gateway-rtpbroadcast#136]

**Comment by njam** [comment]
@notedit we *are* using this plugin in production, with multiple high resolution streams 24/7. But we are *not* actively maintaining it anymore, only applying fixes.
We'd happily accept new maintainers!

**Comment by notedit** [comment]
thanks  @njam  

i will do more test,   if it can fit all our demands,  i am happy  to be one  maintainer.
