### ISSUE TITLE
[ERR] [janus.c:main:3924] The 'janus.plugin.cm.rtpbroadcast' plugin was compiled against an older version of the API (5 < 8), update it to enable it again

### ISSUE THREAD

**Issue by notedit** [cargomedia/janus-gateway-rtpbroadcast#137]
it seems that  rtpbroadcast is a little outdate.

will try to fix this.

**Comment by notedit** [comment]
another  question,

if i update janus rtpbroadcast to the latest janus api, will you merge it?

**Comment by Akagi201** [comment]
@notedit Nice. Good to see a PR.
