### ISSUE TITLE
plugin.h not found

### ISSUE THREAD

**Issue by Fuzzyma** [cargomedia/janus-gateway-rtpbroadcast#138]
I followed the instruction to compile this plugin. But when I do `make` I get 

> libjanus_rtpbroadcast.c:110:26: fatal error: janus/plugin.h: No such file or directory

What do I have to do to make this work? Do I have to add the janus header to something?

**Comment by njam** [comment]
I think you will have to download the Janus source files first by running `get-janus-headers.sh`.
This seems not to be documented correctly in the README, but you can see how to fully build the project in both `.travis.yml` and `Vagrantfile`.
