### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/janus-gateway-rtpbroadcast#17]
Let's track configuration which should be persistent in the config file.

Configs:
- [x] port range for mountpoint audio/video
- [x] default path for storing records
- [ ] ~~enable/disable super-user/super-session support~~

@tomaszdurka what should we configure regarding `cm-janus`? Probably nothing?

**Comment by landswellsong** [comment]
@kris-lab updated to reflect actual functionality

**Comment by kris-lab** [comment]
done for now
