### ISSUE TITLE
Supersession authentication

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/janus-gateway-rtpbroadcast#18]
@tomaszdurka 

Should we introduce some authentication for super `commands`? I would suggest to:
- or introduce `token` which would be stored in `Janus` config file and would be known by `cm-janus`!
- or you would blacklist all messages with not allowed `command` name at proxy layer!

wdyt?

**Comment by kris-lab** [comment]
Also @landswellsong @njam @vogdb @fvovan wdyt?

**Comment by fvovan** [comment]
@kris-lab , what is super `commands`? Isn't it admin/monitor interface?
If true then it already has `admin-secret` setting.

**Comment by kris-lab** [comment]
It is `request` send from e.g. browser to `Janus` via `cm-janus`. Basically it is websocket message in our case. This message is like:
- `watch`
- `create`
- `attach`
- `list`
- etc..

We are gonna introduce next `request/message/command` type which would be `switch-source`. It will allow to switch not the `mounpoint` (entire performance) but it will change only the quality by switching `source` in the `mounpoint`. Currently the structure is:
- `mountpoint` is created per publisher and keep real RTP streams called `sources` in one structure. It can manage unlimited number of sources (e.g. qualities)
- `source` is real RTP entry point. It is part of `mountpoint`. 

@fvovan is my answer understandable?

**Comment by fvovan** [comment]
Yes, thanks,  it makes sense.
But why we can't use existing authentication system (with tokens)? I mean https://janus.conf.meetecho.com/docs/auth.html#token. I think we even could inject this value in cm-janus handlers to not expose it to client's browser.  Doesn't it match to our requirements or will this `switch-source` request have separate auth?

**Comment by kris-lab** [comment]
The idea was to have or any auth mechanism in the plugin itself (without touching core of janus) or do blacklist messages on the `cm-janus`! 

@fvovan I agree, it could be done by core authentication as well, I guess! @landswellsong wdyt? Can we reuse Janus authentication mechanism to manage `superuser session commands`?

**Comment by kris-lab** [comment]
@tomaszdurka any input?

**Comment by vogdb** [comment]
will be done in #20

**Comment by kris-lab** [comment]
As discussed with @tomaszdurka @dlondero let's go with `TOKEN` auth!

**Comment by dlondero** [comment]
Wasn't me! :P

**Comment by kris-lab** [comment]
@dlondero sorry!

**Comment by kris-lab** [comment]
Not needed anymore. See https://github.com/cargomedia/janus-gateway-rtpbroadcast/issues/16#issuecomment-155750488
