### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/janus-gateway-rtpbroadcast#2]
##### Start publishing
Request:
- number of mountpoints
 - params
- whitelisted IPs (maybe replace with SRTP)
- streamChannelKey -> MOUNTPOINT_GROUP
- record?

Response:
- mountpoints
 - port video per mountpoint (autogenerated)
 - port audio per mountpoint (autogenerated)

Questions:
- First group video/audio port will be recorded one!
- should we disable recording for development VM?

Reuse "create"

##### Unpublishing
Websocket close it. 

##### Start subscribing
Request:
- streamChannelKey (it will be instead of mountpoint-id)

Response:
Stay the same.

Reuse "watch"

##### Unsubscribe
Websocket close it.

##### Stop/Kill publisher
Websocket close it.

##### Stop/Kill subscriber
Websocket close it.

###### Thumbnailer
- RTP server?
- Dump to file, convert using Gstreamer?
- cm-janus upload to S3?

Event:
- "thumbnail"
 - "streamChannelKey"
 - "filename"

**Comment by landswellsong** [comment]
Terminology suggestion (discussed with @njam), currently the mountpoint structure is laid out like
```
struct mountpoint {
    struct source {
        fd and port for video
        fd and port for audio
    }
    struct codecs {
        codec for video
        codec for audio
    }
}
```

Making another structure (mountpoint group) would complicate matters unnecessarily, so I suggest we just re-use the mountpoint structure and just have:
- an array of video sources
- 1 audio source
- codecs moved into respective source structure since they can differ between video streams right?

So the end result would look like this:
```
struct mountpoint {
    struct audio {
        fd and port for audio
        codec for audio
    }
    struct video [N] {
        fd and port for video
        codec for video
    }
}
```

**Comment by kris-lab** [comment]
Both `audio` and `video` can have different codecs per mountpoint! So the mountpoint should describe pair of video/audio codec in my opinion. E.g we can stream WebM (VP8+Opus) or MP4 (h264+AAC) but not VP8+ACC or h264+Opus.

With current approach there is a risk to mix the media containers which would not work (WebM, MPEG etc)? Of course the Janus supports only VP8/opus now but it might change?

@landswellsong what is the problem with new structure?
@njam wdyt?

**Comment by landswellsong** [comment]
@kris-lab no problem really, but after removing everything unnecessary and general out of mountpoint structure there's almost nothing left so I thought it would be wiser just to reuse mountpoint struct. We can implement multiple codecs just fine this way too

**Comment by landswellsong** [comment]
Graphical representation of what I mean

[Untitled Diagram.pdf](https://github.com/cargomedia/janus-gateway-rtpbroadcast/files/24754/Untitled.Diagram.pdf)

**Comment by kris-lab** [comment]
Agree, it makes sense to me! @njam please have a look as well

**Comment by landswellsong** [comment]
Thx, I'll stick to this now.

**Comment by njam** [comment]
lgtm!

**Comment by kris-lab** [comment]
Update! We have implement quite few things:
- publisher end-point
- subscriber end-point
- switching

We have too implement with high priority `1`:
- archiver #8 
- thumbnailer #9 
- IP filter for RTP stream #6 

We have too implement with priority `2`:
- key-frame detection #13 
- performance optimisation #12

**Comment by landswellsong** [comment]
@kris-lab @njam important question, how do I contact `cm-janus` for events which are initiated in plugin code?

**Comment by kris-lab** [comment]
Updated priorities https://github.com/cargomedia/janus-gateway-rtpbroadcast/issues/2#issuecomment-154049115

**Comment by kris-lab** [comment]
Updated priorities for still waiting tickets. Discussed with @landswellsong 

Let's try to estimate ETA for stuff we need to test on Sunday/Monday:

1st priority:
- [ ] streaming: Recording: auto thumbnailer + event notification
- [ ] audioroom: Recording: auto recording and event notification

2nd priority:
- [ ] streaming: Switching threshold
- [ ] streaming: Publish: RTP inbound IP filtering/authentication
- [ ] streaming: Persistence layer for admin notification (super-user)
- [ ] audioroom: Persistence layer for admin notification (super-user)

3rd priority:
- [ ] streaming: RTP: detect keyframe in the stream
- [ ] streaming: Performance: investigate throughput throttling

**Comment by kris-lab** [comment]
Update.

> (copying Oleksiy mail)
Hello,
Sorry I had to relocate faster than I though and I wanted to finish what I have. 
- Issue #6 (ip filtering), works and tested
- Issue #28 (stop recording at session breaking) works for my setup, tested
- Git mess fixed. Sorry about that, took a long time to figure out. 
- Currently pushing the stop-on-breaking session fix for audio and fixes for bugs reported, needed a clean git for this. 
- Switching underway, I was too delayed by breaking the git, feel very sorry but I think time isn't running out yet.

>Kind regards,

@landswellsong Let's try to finish switching today, so we can test full pipeline soon.

**Comment by njam** [comment]
@kris-lab still relevant?

**Comment by kris-lab** [comment]
Can be closed. Anyway looks good. The only untouched thing is "Performance: investigate throughput throttling".
