### ISSUE TITLE
Scaling ideas

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/janus-gateway-rtpbroadcast#40]
Part of https://github.com/cargomedia/puppet-cargomedia/issues/1080

META:
- [ ] UDP client #64
- [ ] Mountpoint info for create/destroy #65

**Comment by kris-lab** [comment]
![janus-gateway-rtpbroadcast - new page](https://cloud.githubusercontent.com/assets/1843523/11762271/fe697438-a0e0-11e5-87fc-73b58ee2f773.png)

**Comment by kris-lab** [comment]
Interesting https://altanaitelecom.wordpress.com/2015/08/07/webrtc-live-stream-broadcast/

**Comment by kris-lab** [comment]
Also please have a look here https://github.com/cargomedia/puppet-cargomedia/issues/1006#issuecomment-169764117

**Comment by landswellsong** [comment]
@kris-lab wow, great link :+1:

**Comment by kris-lab** [comment]
Plan/notes for changes (beta, will be edited and discussed)

- configuration file
 - add mode: origin, edge
 - add server-id: string
 - add origin hostname: ip/fqdn

- global variables
 - listeners_udp = []

- implements UDP_Client()
 - sends data to the udp server

- extends "cm_rtpbcast_session" struct
 - add "relay_type": webrtc, udp
 - add "realy_options" based on type - for UDP would be video-port, audio-port, IP

- extends "cm_rtpbcast_relay_thread"
 - loop additionally over "listeners_udp" array (sessions)
 - call cm_rtpbcast_relay_rtp_over_udp(packet, session) for each listener

- implements "cm_rtpbcast_relay_rtp_over_udp(packet, session)"
 - receives rap packet to send
 - read UDP destination from "cm_rtpbcast_session": realy_options
 - uses UDP_client to send data

- extends end-point/actions:
 - "watch-udp"
   - add session to the "listeners_udp" array
    - requires to receive the mount point definition (ID, video/audio-port, IP)
 - "stop-udp"
   - removes session from the "listeners_udp" array
 - "mountpoint-update"
   - upgrade session/ws to receive updates about every mount point create/destroy

cc @njam @landswellsong

**Comment by kris-lab** [comment]
@landswellsong fyi, the orchestration logic which handles replications of mountpoints, starting the `watch-udp`, reading the state etc will be done in https://github.com/cargomedia/cm-janus/issues/183

**Comment by landswellsong** [comment]
@kris-lab @njam 
fyi https://blog.cloudflare.com/how-to-receive-a-million-packets/

**Comment by ppp0** [comment]
very interesting read, thanks @landswellsong

**Comment by njam** [comment]
Closeable in favor of https://github.com/cargomedia/puppet-cargomedia/issues/1080 ?

**Comment by kris-lab** [comment]
yes!
