### ISSUE TITLE
Profiling analysis

### ISSUE THREAD

**Issue by landswellsong** [cargomedia/janus-gateway-rtpbroadcast#44]
For https://github.com/cargomedia/janus-gateway-rtpbroadcast/issues/12

Steps to gather data:
1. 
```
apt-get install vallgrind
cd /path/you/want/collected/data/to/go
valgrind --tool=callgrind --trace-children=yes /path/to/janus/bin/janus
```
2. Load it with work
3. 
```
apt-get install kcachegrind
kcachegrind callgrind.out.<PID>
```

Other `oprofile`/`callgrind` tools will also work, `kcachegrind` is an example, manual at: https://kcachegrind.github.io

@kris-lab @njam FYI

PS: we might need a version of the source without `static` keywords around `rtpbcast` functions, but this is pretty trivial to prepare.

**Comment by kris-lab** [comment]
For osx use
```
brew install qcachegrind --with-graphviz
```

**Comment by njam** [comment]
Closing in favor of https://github.com/cargomedia/janus-gateway-rtpbroadcast/issues/68
