### ISSUE TITLE
Mountpoints not immediately destroyed on websocket disconnect

### ISSUE THREAD

**Issue by njam** [cargomedia/janus-gateway-rtpbroadcast#47]
When restarting cm-janus during a video stream, when trying to re-establish the same mountpoint janus usually responds with:
> A stream with the provided ID already exists

To me it looks like janus is not dropping the mountpoints when the WS connection is closed.

@kris-lab could you double-check? Is it happening delayed? Can it be fixed easily?

**Comment by kris-lab** [comment]
All works fine on Janus and plugin level. Janus needs time to cleanup Webrtc after Websocket drops. Some of the time is taken by closing the file with dumped RTP packets. Probably it can be optimised but not too much IMO. Also when mountpoint drops there are many events triggered for each connected listener. 

Will investigate if neccessary but I don see to much room for optimisation.

**Comment by njam** [comment]
Ok, let's ignore it for now
