### ISSUE TITLE
Do not create thumbnail job descriptions with mjr file without keyframe

### ISSUE THREAD

**Issue by tomaszdurka** [cargomedia/janus-gateway-rtpbroadcast#55]

**Comment by njam** [comment]
Idea from yesterday: start thumbnailing when a keyframe is detected, and stop thumbnailing when the next one arrives (or the one after that). This way we should always have exactly 1 keyframe and all the interframes before the next keyframe.

**Comment by tomaszdurka** [comment]
That would maybe allow to remove hack for mj2png ('test -f') as well.

**Comment by landswellsong** [comment]
@tomaszdurka @njam IIRC from discussion on the office, we are now rather making it like this:
1. When thumbnailing time comes, wait for next keyframe.
2. When keyframe arrives, dump all of it's parts.
3. Sleep for next interval.

Is that correct? Implementing now.

**Comment by njam** [comment]
sgtm

**Comment by kris-lab** [comment]
will be done in https://github.com/cargomedia/janus-gateway-rtpbroadcast/pull/80

closing.
