### ISSUE TITLE
Make sure to not create job descriptions without actual mjr files dumped

### ISSUE THREAD

**Issue by tomaszdurka** [cargomedia/janus-gateway-rtpbroadcast#56]
I have this `.json` file which points to nonexistent mjr video file. Please make sure that you don't create descriptions without it.

**Comment by njam** [comment]
This happened again. A job file was created referencing a MJR thumbnail file, which doesn't exist.

@kris-lab any idea what could cause this, or how to further debug?

**Comment by kris-lab** [comment]
Will be done in https://github.com/cargomedia/janus-gateway-rtpbroadcast/pull/80.

closing.
