### ISSUE TITLE
Scalability benchmarks

### ISSUE THREAD

**Issue by njam** [cargomedia/janus-gateway-rtpbroadcast#68]
RTP experiment 1:
- 1 instance with 1x janus:
 - A: "origin"
- 1 big instance with 2x janus:
 - B: "repeater"
 - C: x-times "edge"
- 1 browser client D
- 1 inbound RTP stream to A (5mbit/s from local gstreamer)
- 1 RTP forward from A to B
- X RTP forward from B to C
- 1 outbound WebRTC client from C to D
- Forward RTP stream from A to B (create "mountpoint", then "watch-udp")
 - Multiply this *forwarding* multiple times, until the video on WebRTC drops in quality
- **Questions**:
 - How many *forwardings* can be established before quality drops? If above 5Gbps -> don't care
 - What is the resource (CPU) usage?

RTP experiment 2:
- Same as above, but with 10 inbound RTP streams

---

WebRTC experiment 1:
- 1 big instance with 1x janus A
- Some instances with browser clients 100x B
- 1 browser client C
- 1 inbound RTP stream to A (5mbit/s from local gstreamer)
- 100x outbound WebRTC client from A to B
- 1 outbound WebRTC client from A to C
- **Questions**:
 - How many outbound WebRTC streams possible until the video quality drops?
 - What is the resource (CPU) usage

WebRTC experiment 2:
- Same as above, but with 10 inbound RTP streams

---

Thoughts:
- Add test plans to https://github.com/cargomedia/janus-testing
- Use vagrant on AWS: https://github.com/cargomedia/vagrant-boxes
- Add "browser{1,2,3}" instance on janus-testing: https://github.com/cargomedia/janus-testing/issues/3

**Comment by kris-lab** [comment]
Testing scenarios must evolve and logging must improved as defined https://github.com/cargomedia/janus-testing/issues/11

please reopen if disagree

**Comment by njam** [comment]
Agree, btw let's do the next tests with 15mbps (for multiple streams).

**Comment by kris-lab** [comment]
ok

**Comment by kris-lab** [comment]
> WebRTC experiment 1 / RTP experiment 1

Experiment have been done. See more https://github.com/cargomedia/puppet-cargomedia/issues/1080#issuecomment-228379581

> RTP experiment 2 / WebRTC experiment 2

Experiment have been done with 5 inbound streams (instead of 10). See more https://github.com/cargomedia/puppet-cargomedia/issues/1080#issuecomment-228379581
