### ISSUE TITLE
Crash in cm_rtpbcast_mountpoint_destroy ()

### ISSUE THREAD

**Issue by pongponglau** [cargomedia/janus-gateway-rtpbroadcast#86]
This plugin is very nice. Thanks for your great effort.

I find that the Janus instance will be crashed when i destroy the mountpoint. May i ask if you have the same issue? If so, is there any fix?

Thanks a lot

**Comment by pongponglau** [comment]
Sorry, no problem with this function. It is my fault.

Thanks a lot

**Comment by kris-lab** [comment]
@pongponglau anyway thanks for testing. Any feedback is very welcome!
