### ISSUE TITLE
Get mountpoint streams in response to a "watch" request

### ISSUE THREAD

**Issue by zazabe** [cargomedia/janus-gateway-rtpbroadcast#87]
The client should receive all available streams in response to `watch` or `switch` requests.
This will help to list streams before the first `mountpoint-info` event on the client side.

- response after a "watch" request   
  <img width="827" alt="screen shot 2016-04-25 at 19 16 18" src="https://cloud.githubusercontent.com/assets/401598/14783791/37f6eb18-0b1c-11e6-9576-f98e9c24790c.png">    

- "mountpoint-info" data    
  <img width="771" alt="screen shot 2016-04-25 at 19 16 53" src="https://cloud.githubusercontent.com/assets/401598/14783958/454ec9f6-0b1d-11e6-8dc8-f650a868914b.png">

_note: I'm using the `master` source of the rtpbroadcast plugin_

**Comment by kris-lab** [comment]
There is `list` end-point which return this informations. Maybe we could use it instead of extending `watch` and `switch`?

**Comment by zazabe** [comment]
I thought about it again, `list` seems the right choice, we could use it to switch between mountpoints later also... but is it accessible without being a `superuser`?

**Comment by kris-lab** [comment]
yes, `list` is available for everyone.

**Comment by zazabe** [comment]
ok, so let's close this PR! ;)
