### ISSUE TITLE
META: Upgrade to newest janus

### ISSUE THREAD

**Issue by njam** [cargomedia/janus-gateway-rtpbroadcast#89]
see also meetecho/janus-gateway#492

Plugins:
- [ ] https://github.com/cargomedia/puppet-cargomedia/issues/1052

**Comment by kris-lab** [comment]
more new stuff [event handler plugins](https://github.com/meetecho/janus-gateway/pull/536)

**Comment by njam** [comment]
Closing, will be done later all at once
