### ISSUE TITLE
Avoid autoswitch going up and down repeatedly

### ISSUE THREAD

**Issue by njam** [cargomedia/janus-gateway-rtpbroadcast#91]
First: determine if this is a real problem, and how it behaves exactly (https://github.com/cargomedia/sk/issues/2891).

The idea with average/delay on the janus side was to prevent too quick switching. What about we replace this logic with immediate switch but based on some "hysteresis loop" where we have some range of sensitivity to upgrade/downgrade in bit/s?

![](http://www.nature.com/nature/journal/v521/n7552/images/521298a-f1.jpg)

Agree this could be solved with such a hysteresis loop, in our case with fixed levels it could look like this:
<img src="https://cloud.githubusercontent.com/assets/360800/15464090/7d4a7588-20cd-11e6-927f-0e700cc3556b.jpg" height=300>

**Comment by kris-lab** [comment]
This gonna be done on the client side. closing for the moment.
