### ISSUE TITLE
h264 support

### ISSUE THREAD

**Issue by hasbean** [cargomedia/janus-gateway-rtpbroadcast#92]
I noticed that only VP8 is supported for keyframing, etc. h264 support is gaining traction with Chrome enabling it soon (it's working on Canary)

Are there any plans for this?

**Comment by kris-lab** [comment]
@hasbean sorry for late response. 

I cannot confirm any date of adding the support for h264. However, it could be a part of the upgrade to the newest Janus features (tracking ticket https://github.com/cargomedia/janus-gateway-rtpbroadcast/issues/89).

There is a support for VP8/h264 in the official `streaming` plugin already. Please see https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_streaming.c#L3508 so I think it should be straight forward to re-use some of this code.

cc @njam

**Comment by harris** [comment]
Is supporting H264 on the roadmap?  Would love to get a hold of it when it's released.

**Comment by kris-lab** [comment]
Sorry, this is not on the roadmap at the moment. We have higher priorities, however it might change in the future. I will update here once we start discussion about other codecs: h264, vp9.

**Comment by njam** [comment]
We won't implement this at the moment. Pull requests welcome!
